'use client'
import {useMemo,useState} from 'react'
import {ArrowRight,ChevronDown,Heart,Instagram,Menu,Search,ShoppingBag,Star,X} from 'lucide-react'

const products=[
 {id:1,name:'Khair Pistachio',brand:'Paris Corner',price:32000,tag:'BESTSELLER',tone:'pistachio',notes:'Pistachio · Cream · Vanilla',desc:'A creamy gourmand scent with a playful, luxurious finish.'},
 {id:2,name:'Supremacy Collector',brand:'Afnan',price:58000,tag:'SIGNATURE',tone:'amber',notes:'Fruity · Woody · Amber',desc:'Polished, confident and made to leave a memorable trail.'},
 {id:3,name:'Invicto Legend',brand:'Fragrance World',price:38000,tag:'NEW',tone:'smoke',notes:'Fresh · Aromatic · Woody',desc:'A bold everyday fragrance with a clean, energetic character.'},
 {id:4,name:'Almas Perfume Oil',brand:'Jessy Selection',price:12000,tag:'OIL',tone:'rose',notes:'Warm · Floral · Musk',desc:'An intimate oil blend designed for close-to-skin luxury.'},
]
function Bottle({tone='amber'}:{tone?:string}){return <div className={'bottle '+tone}><div className="cap"/><div className="neck"/><div className="glass"><div className="label">JESSY<br/><span>LUXURY</span></div></div></div>}
function ProductCard({p}:{p:any}){const [liked,setLiked]=useState(false);return <article className="group relative"><div className="relative aspect-[4/5] overflow-hidden rounded-[2px] bg-[#eee8dc] flex items-center justify-center"><span className="absolute left-4 top-4 z-10 text-[10px] tracking-[.22em] font-bold">{p.tag}</span><button onClick={()=>setLiked(!liked)} className="absolute right-4 top-4 z-10 rounded-full bg-white/70 p-2 backdrop-blur"> <Heart size={15} fill={liked?'#0D0B0A':'none'}/></button><div className="scale-[.8] transition duration-700 group-hover:scale-[.9]"><Bottle tone={p.tone}/></div><div className="absolute inset-x-4 bottom-4 flex translate-y-3 justify-center opacity-0 transition group-hover:translate-y-0 group-hover:opacity-100"><a href={`https://wa.me/?text=${encodeURIComponent('Hello Jessy Luxury, I want to order '+p.name)}`} className="w-full bg-ink text-white text-center py-3 text-[11px] tracking-[.18em]">ORDER VIA WHATSAPP</a></div></div><div className="pt-5"><p className="text-[10px] uppercase tracking-[.2em] text-black/45">{p.brand}</p><h3 className="serif text-xl mt-1">{p.name}</h3><p className="text-xs text-black/55 mt-2">{p.notes}</p><p className="mt-3 font-semibold">₦{p.price.toLocaleString()}</p></div></article>}
export default function Home(){const [open,setOpen]=useState(false);const [query,setQuery]=useState('');const filtered=useMemo(()=>products.filter(p=>(p.name+p.brand+p.notes).toLowerCase().includes(query.toLowerCase())),[query]);return <main>
<header className="fixed top-0 z-50 w-full border-b border-black/10 bg-ivory/90 backdrop-blur-xl"><div className="mx-auto flex h-[74px] max-w-7xl items-center justify-between px-5 lg:px-10"><button className="lg:hidden" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><a href="#" className="serif text-xl tracking-[.18em]">JESSY <span className="text-champagne">LUXURY</span></a><nav className="hidden items-center gap-9 lg:flex text-[11px] tracking-[.16em]"><a href="#shop">SHOP</a><a href="#collections">COLLECTIONS</a><a href="#story">ABOUT</a><a href="#finder">FIND YOUR SCENT</a></nav><div className="flex items-center gap-3"><button onClick={()=>document.getElementById('search')?.focus()}><Search size={18}/></button><a href="#shop"><ShoppingBag size={18}/></a></div></div>{open&&<div className="lg:hidden border-t border-black/10 px-6 py-7 space-y-5 text-sm"><a className="block" href="#shop" onClick={()=>setOpen(false)}>SHOP</a><a className="block" href="#collections" onClick={()=>setOpen(false)}>COLLECTIONS</a><a className="block" href="#story" onClick={()=>setOpen(false)}>ABOUT</a><a className="block" href="#finder" onClick={()=>setOpen(false)}>FIND YOUR SCENT</a></div>}</header>
<section className="relative min-h-[760px] overflow-hidden pt-[74px] bg-ink text-ivory"><div className="absolute inset-0 opacity-20 grain"/><div className="absolute -right-32 top-20 h-[620px] w-[620px] rounded-full bg-[#6d5435]/30 blur-3xl"/><div className="relative mx-auto grid min-h-[686px] max-w-7xl items-center px-6 lg:grid-cols-2 lg:px-10"><div className="max-w-xl py-20"><p className="mb-6 text-[10px] tracking-[.42em] text-champagne">JESSY LUXURY FRAGRANCE</p><h1 className="serif text-6xl leading-[.93] sm:text-7xl lg:text-[94px]">SMELL<br/><em className="font-normal text-[#d9c5a2]">EXPENSIVE.</em></h1><p className="mt-8 max-w-md text-sm leading-7 text-white/65">Curated Arabic, designer and everyday luxury fragrances for the moments you want to be remembered.</p><div className="mt-10 flex flex-wrap gap-3"><a href="#shop" className="bg-champagne px-7 py-4 text-[10px] font-bold tracking-[.22em] text-ink">SHOP THE COLLECTION</a><a href="#finder" className="border border-white/25 px-7 py-4 text-[10px] tracking-[.22em]">FIND YOUR SCENT</a></div></div><div className="flex justify-center lg:justify-end"><div className="relative flex h-[500px] w-[420px] items-center justify-center"><div className="absolute h-[380px] w-[380px] rounded-full border border-champagne/30"/><div className="absolute h-[310px] w-[310px] rounded-full border border-white/10"/><div className="scale-[1.45]"><Bottle tone="amber"/></div></div></div></div></section>
<section id="collections" className="border-b border-black/10 bg-ivory py-20"><div className="mx-auto max-w-7xl px-6 lg:px-10"><div className="flex items-end justify-between"><div><p className="text-[10px] tracking-[.3em] text-champagne">DISCOVER</p><h2 className="serif mt-3 text-4xl sm:text-5xl">Your signature scent.</h2></div><a href="#shop" className="hidden items-center gap-2 text-[10px] tracking-[.2em] sm:flex">VIEW ALL <ArrowRight size={15}/></a></div><div className="mt-12 grid grid-cols-2 gap-3 lg:grid-cols-4">{['ARABIC','DESIGNER','PERFUME OILS','GIFT SETS'].map((x,i)=><a href="#shop" key={x} className="group relative aspect-[3/4] overflow-hidden bg-[#e7dfd1]"><div className="absolute inset-0 transition duration-700 group-hover:scale-105" style={{background:`radial-gradient(circle at ${30+i*18}% ${25+i*10}%, rgba(201,163,93,.35), transparent 35%), linear-gradient(145deg,#efe9de,#c7baa7)`}}/><div className="absolute inset-0 flex items-end p-5"><span className="text-xs tracking-[.2em]">{x}</span></div></a>)}</div></div></section>
<section id="shop" className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="text-[10px] tracking-[.3em] text-champagne">THE EDIT</p><h2 className="serif mt-3 text-4xl sm:text-5xl">Customer favourites</h2></div><div className="relative w-full sm:w-64"><Search size={15} className="absolute left-0 top-3"/><input id="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search fragrances" className="w-full border-b border-black/20 bg-transparent py-2 pl-7 text-xs outline-none"/></div></div><div className="mt-14 grid grid-cols-2 gap-x-4 gap-y-14 md:grid-cols-4 md:gap-x-6">{filtered.map(p=><ProductCard key={p.id} p={p}/>)}</div></section>
<section id="story" className="bg-[#e9e0d1] py-24"><div className="mx-auto grid max-w-7xl gap-12 px-6 lg:grid-cols-2 lg:px-10"><div className="flex items-center justify-center min-h-[420px] bg-ink"><div className="text-center text-ivory"><p className="text-[10px] tracking-[.35em] text-champagne">THE JESSY STANDARD</p><p className="serif mt-6 text-5xl">Luxury is how<br/><em className="font-normal text-[#d9c5a2]">you show up.</em></p></div></div><div className="flex flex-col justify-center"><p className="text-[10px] tracking-[.3em] text-champagne">ABOUT JESSY LUXURY</p><h2 className="serif mt-4 text-4xl leading-tight sm:text-5xl">A fragrance should feel like part of your identity.</h2><p className="mt-6 max-w-lg text-sm leading-7 text-black/60">From carefully selected Arabic and designer fragrances to oils and gift sets, Jessy Luxury helps you choose a scent that fits your personality, occasion and lifestyle.</p><div className="mt-8 flex gap-8 text-[10px] tracking-[.18em]"><span>AUTHENTIC SELECTION</span><span>WHATSAPP SUPPORT</span></div></div></div></section>
<section id="finder" className="bg-ink py-24 text-ivory"><div className="mx-auto max-w-5xl px-6 text-center"><p className="text-[10px] tracking-[.35em] text-champagne">NOT SURE WHAT TO CHOOSE?</p><h2 className="serif mt-5 text-5xl sm:text-6xl">Find your scent.</h2><p className="mx-auto mt-5 max-w-xl text-sm leading-7 text-white/55">Choose the mood and we’ll point you toward the right part of the collection.</p><div className="mt-10 flex flex-wrap justify-center gap-3">{['ROMANTIC','BOLD','FRESH','SWEET','ELEGANT','EVERYDAY'].map(x=><a key={x} href="#shop" className="border border-white/15 px-6 py-4 text-[10px] tracking-[.2em] transition hover:border-champagne hover:text-champagne">{x}</a>)}</div></div></section>
<footer className="bg-ivory px-6 py-16"><div className="mx-auto max-w-7xl"><div className="grid gap-10 md:grid-cols-4"><div><a className="serif text-xl tracking-[.16em]">JESSY LUXURY</a><p className="mt-4 max-w-xs text-xs leading-6 text-black/50">Smell expensive. Feel unforgettable.</p></div><div><p className="text-[10px] tracking-[.2em] font-bold">SHOP</p><div className="mt-4 space-y-3 text-xs text-black/60"><a className="block" href="#shop">All fragrances</a><a className="block" href="#collections">Collections</a><a className="block" href="#finder">Find your scent</a></div></div><div><p className="text-[10px] tracking-[.2em] font-bold">HELP</p><div className="mt-4 space-y-3 text-xs text-black/60"><a className="block" href="#">Delivery & pickup</a><a className="block" href="#">FAQ</a><a className="block" href="https://wa.me/">WhatsApp</a></div></div><div><p className="text-[10px] tracking-[.2em] font-bold">FOLLOW</p><a href="#" className="mt-4 flex items-center gap-2 text-xs text-black/60"><Instagram size={15}/> Instagram</a></div></div><div className="gold-line my-10"/><div className="flex flex-col justify-between gap-3 text-[10px] tracking-[.1em] text-black/40 sm:flex-row"><span>© 2026 Jessy Luxury Fragrance</span><span>Designed for a luxury-first shopping experience.</span></div></div></footer>
<style jsx global>{`.bottle{position:relative;width:120px;height:250px}.cap{position:absolute;z-index:3;left:39px;top:0;width:42px;height:36px;border-radius:4px 4px 2px 2px;background:linear-gradient(90deg,#171412,#5c4c39,#15120f);box-shadow:0 5px 15px #0004}.neck{position:absolute;z-index:2;left:47px;top:31px;width:26px;height:34px;background:linear-gradient(90deg,#8d7a5d,#e1cda5,#8b7657)}.glass{position:absolute;left:10px;top:58px;width:100px;height:175px;border-radius:16px 16px 22px 22px;background:linear-gradient(90deg,#1b120b,#9b6b2f 40%,#e7bf73 55%,#25160b);box-shadow:inset 9px 0 14px #fff2, inset -12px 0 25px #0008, 0 20px 30px #0003}.pistachio .glass{background:linear-gradient(90deg,#35412c,#b4b681,#596443)}.smoke .glass{background:linear-gradient(90deg,#111,#5c625d,#171717)}.rose .glass{background:linear-gradient(90deg,#4d1e2a,#c48b8e,#6b2632)}.label{position:absolute;left:15px;right:15px;top:67px;border:1px solid #d9c5a2aa;text-align:center;padding:11px 3px;color:#ead8b6;font-family:Georgia,serif;font-size:12px;letter-spacing:.2em}.label span{font-size:7px;letter-spacing:.28em}`}</style>
</main>}
